spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:spring-guide
      username: sa
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    hikari:
      jdbc-url: postgresql://localhost:5432/renuevo_db
      username: renuevo
      password: ${db.pass:NONE}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    hikari:
      jdbc-url: postgresql://localhost:5432/renuevo_db
      username: renuevo
      password: ${db.pass:NONE}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
